first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")
email = input("Enter your email address: ")
phone = input("Enter your phone number: ")
job_title = input("Enter your job title: ")
id_number = input("Enter your ID number: ")

new_last_name = last_name.upper()
new_job_title = job_title.capitalize()
new_email_address = email.lower()
new_first_name = first_name.title()

print("The ID Card is:")
print("\n----------------------------------------")
print(f"{new_last_name}, {first_name}")
print(f"{new_job_title}")
print(f"ID: {id_number}")
print(f"\n{new_email_address}")
print(f"{phone}")
print("----------------------------------------\n")
